services:
  thunders.techtest.apiservice:
    image: thunders.techtest.apiservice
    build:
      context: .
      dockerfile: Thunders.TechTest.ApiService/Dockerfile
      
  thunders.techtest.database:
    image: postgres:latest
    environment:
      POSTGRES_USER: thunders
      POSTGRES_PASSWORD: thunders
      POSTGRES_DB: tollDB
    ports:
      - "5432:5432"
    restart: unless-stopped
  

